# Generated by Django 5.1.4 on 2024-12-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_proj1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
